---
baseurl: "https://tsaikd.org/blog/"
title: "TsaiKD Blog"
menu:
  main:
    - name: GitHub
      url: https://github.com/tsaikd
  social:
    - pre: "<i class='fa fa-facebook'></i>"
      url: https://www.facebook.com/tsaikd
      identifier: facebook
params:
  sidebartitle: "TsaiKD Blog"
  totop: true
  noread: true
  socialsharing: true
  gaid: UA-151772-4
---
